apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: credicard-validation
  # This is an extra long description
  description: An apllication that validates creditcard.
  links:
    - url: https://github.com/juliusshrestha/creditcardvalidator
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: julius-shrestha
  providesApis:
    - backstage-demo
  consumesApis:
    - backstage-demo
    
